### ISSUE TITLE
Creating the pcb

### ISSUE THREAD

**Issue by slugb0t** [yiancar/Seigaiha#1]
Hi I'm fairly new to custom keyboards but have been eyeing this pcb for my build. I'm wondering on how do I go about getting this design created for me? Are there any recommended companies to go through or sites that provide services for this? If so is just providing them the GitHub link or what is required for creating this into a PCB?

Any help is appreciated, thank you!

**Comment by yiancar** [comment]
Hello @slugb0t.

I will answer by saying you can buy our kit with all the components as well as with building instructions:)
https://mykeyboard.eu/catalogue/seigaiha-kit_4821/
https://novelkeys.com/products/seigaiha-keyboard-kit
https://mechboards.co.uk/products/seigaiha-kit

In case you still want to manufacture this for your own personal use, the files must be opened with KiCAD, you need to exports the gerbers and then send them to a PCB manufacturer. Also you would need all the components and program the MCU with the bootloader.

I hope this helps!
Cheers,
Yiangos

**Comment by slugb0t** [comment]
Thank you @yiancar for providing the links! I had been on novelkeys but they haven't been in stock in a while now so I was trying to find other places! Went with mechboards and even though they reside in the UK I got my package within the week. Thanks for designing a cool looking board! Excited to create my build with this!

**Comment by yiancar** [comment]
Cheers:) We are trying to ship some more stock to NK in the next months:)
